#############################################################################
# Makefile for building: main.app/Contents/MacOS/main
# Generated by qmake (2.01a) (Qt 4.8.3) on: Sat Dec 15 02:39:28 2012
# Project:  main.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile main.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -DNDEBUG -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I/usr/local/Cellar/qt/4.8.3/mkspecs/macx-g++ -I. -I/usr/local/Cellar/qt/4.8.3/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.3/lib/QtCore.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.3/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.3/lib/QtGui.framework/Versions/4/Headers -I/usr/local/Cellar/qt/4.8.3/include -ImyCurveFit -I/homes/gws/aseem/boost -I/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/System/Library/Frameworks/AGL.framework/Headers -I. -F/usr/local/Cellar/qt/4.8.3/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/usr/local/Cellar/qt/4.8.3/lib -L/usr/local/Cellar/qt/4.8.3/lib KLT/libKLT.a -framework OpenGL -framework AGL -framework QtGui -L/usr/local/Cellar/qt/4.8.3/lib -F/usr/local/Cellar/qt/4.8.3/lib -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.C \
		mymainwindow.C \
		centralWidget.C \
		rotoscope.C \
		imageGraph.C \
		liveWire.C \
		rotoCurves.C \
		imgSequence.C \
		corresponder.C \
		draw.C \
		drawPath.C \
		drawCurves.C \
		rotoPath.C \
		hertzStrokes/Stroke.cpp \
		geigerCorresponder.C \
		abstractPath.C \
		interModule.C \
		myCurveFit/FitCurves.c \
		myCurveFit/GGVecLib.c \
		rangeDialog.C \
		drawCorresponder.C \
		rotoCorresponder.C \
		Texture.C \
		hertzStrokes/bitmap.cpp \
		trackGraph.C \
		drawContCorr.C \
		transformer.C \
		rotoRegion.C moc_mymainwindow.cpp \
		moc_centralWidget.cpp \
		moc_rotoscope.cpp \
		moc_liveWire.cpp \
		moc_draw.cpp \
		moc_interModule.cpp \
		moc_rangeDialog.cpp
OBJECTS       = main.o \
		mymainwindow.o \
		centralWidget.o \
		rotoscope.o \
		imageGraph.o \
		liveWire.o \
		rotoCurves.o \
		imgSequence.o \
		corresponder.o \
		draw.o \
		drawPath.o \
		drawCurves.o \
		rotoPath.o \
		Stroke.o \
		geigerCorresponder.o \
		abstractPath.o \
		interModule.o \
		FitCurves.o \
		GGVecLib.o \
		rangeDialog.o \
		drawCorresponder.o \
		rotoCorresponder.o \
		Texture.o \
		bitmap.o \
		trackGraph.o \
		drawContCorr.o \
		transformer.o \
		rotoRegion.o \
		moc_mymainwindow.o \
		moc_centralWidget.o \
		moc_rotoscope.o \
		moc_liveWire.o \
		moc_draw.o \
		moc_interModule.o \
		moc_rangeDialog.o
DIST          = /usr/local/Cellar/qt/4.8.3/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/g++-base.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/g++-macx.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.3/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/unix/x11.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/unix/x11inc.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/unix/x11lib.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/include_source_dir.prf \
		main.pro
QMAKE_TARGET  = main
DESTDIR       = 
TARGET        = main.app/Contents/MacOS/main

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile main.app/Contents/PkgInfo main.app/Contents/Resources/empty.lproj main.app/Contents/Info.plist $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) main.app/Contents/MacOS/ || $(MKDIR) main.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: main.pro  /usr/local/Cellar/qt/4.8.3/mkspecs/macx-g++/qmake.conf /usr/local/Cellar/qt/4.8.3/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/g++-base.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/common/g++-macx.conf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt/4.8.3/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/release.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/unix/x11.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/unix/x11inc.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/unix/x11lib.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/unix/opengl.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt/4.8.3/mkspecs/features/include_source_dir.prf \
		/usr/local/Cellar/qt/4.8.3/lib/QtGui.framework/QtGui.prl \
		/usr/local/Cellar/qt/4.8.3/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile main.pro
/usr/local/Cellar/qt/4.8.3/mkspecs/common/unix.conf:
/usr/local/Cellar/qt/4.8.3/mkspecs/common/mac.conf:
/usr/local/Cellar/qt/4.8.3/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt/4.8.3/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt/4.8.3/mkspecs/common/g++-base.conf:
/usr/local/Cellar/qt/4.8.3/mkspecs/common/g++-macx.conf:
/usr/local/Cellar/qt/4.8.3/mkspecs/qconfig.pri:
/usr/local/Cellar/qt/4.8.3/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/release.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/unix/x11.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/unix/x11inc.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/unix/x11lib.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/unix/opengl.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/qt.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/moc.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/resources.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/uic.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/lex.prf:
/usr/local/Cellar/qt/4.8.3/mkspecs/features/include_source_dir.prf:
/usr/local/Cellar/qt/4.8.3/lib/QtGui.framework/QtGui.prl:
/usr/local/Cellar/qt/4.8.3/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile main.pro

main.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) main.app/Contents || $(MKDIR) main.app/Contents 
	@$(DEL_FILE) main.app/Contents/PkgInfo
	@echo "APPL????" >main.app/Contents/PkgInfo
main.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) main.app/Contents/Resources || $(MKDIR) main.app/Contents/Resources 
	@touch main.app/Contents/Resources/empty.lproj
	
main.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) main.app/Contents || $(MKDIR) main.app/Contents 
	@$(DEL_FILE) main.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,main,g" -e "s,@TYPEINFO@,????,g" /usr/local/Cellar/qt/4.8.3/mkspecs/macx-g++/Info.plist.app >main.app/Contents/Info.plist
dist: 
	@$(CHK_DIR_EXISTS) .tmp/main1.0.0 || $(MKDIR) .tmp/main1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/main1.0.0/ && $(COPY_FILE) --parents mymainwindow.h centralWidget.h imgSequence.h rotoscope.h dynArray.h jl_vectors.h llist.h geigerCorresponder.h imageGraph.h liveWire.h heap.h rotoCurves.h corresponder.h rotoCorresponder.h draw.h drawPath.h drawCurves.h rotoPath.h abstractPath.h interModule.h myCurveFit/FitCurves.h bBoxf2D.h KLT/klt.h rangeDialog.h drawCorresponder.h gcnode.h pixmaps.h joint.h Texture.h hertzStrokes/Stroke.h hertzStrokes/bitmap.h trackGraph.h KLT/contCorr.h KLT/bezSpline.h KLT/talkFitCurve.h drawContCorr.h transformer.h rotoRegion.h .tmp/main1.0.0/ && $(COPY_FILE) --parents main.C mymainwindow.C centralWidget.C rotoscope.C imageGraph.C liveWire.C rotoCurves.C imgSequence.C corresponder.C draw.C drawPath.C drawCurves.C rotoPath.C hertzStrokes/Stroke.cpp geigerCorresponder.C abstractPath.C interModule.C myCurveFit/FitCurves.c myCurveFit/GGVecLib.c rangeDialog.C drawCorresponder.C rotoCorresponder.C Texture.C hertzStrokes/bitmap.cpp trackGraph.C drawContCorr.C transformer.C rotoRegion.C .tmp/main1.0.0/ && (cd `dirname .tmp/main1.0.0` && $(TAR) main1.0.0.tar main1.0.0 && $(COMPRESS) main1.0.0.tar) && $(MOVE) `dirname .tmp/main1.0.0`/main1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/main1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r main.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_mymainwindow.cpp moc_centralWidget.cpp moc_rotoscope.cpp moc_liveWire.cpp moc_draw.cpp moc_interModule.cpp moc_rangeDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mymainwindow.cpp moc_centralWidget.cpp moc_rotoscope.cpp moc_liveWire.cpp moc_draw.cpp moc_interModule.cpp moc_rangeDialog.cpp
moc_mymainwindow.cpp: imgSequence.h \
		imageGraph.h \
		jl_vectors.h \
		rotoCurves.h \
		rotoPath.h \
		dynArray.h \
		rotoCorresponder.h \
		geigerCorresponder.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h \
		joint.h \
		trackGraph.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		rotoRegion.h \
		drawCurves.h \
		drawPath.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		Texture.h \
		hertzStrokes/bitmap.h \
		drawContCorr.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h \
		centralWidget.h \
		interModule.h \
		rotoscope.h \
		liveWire.h \
		heap.h \
		heap.C \
		transformer.h \
		draw.h \
		rangeDialog.h \
		mymainwindow.h
	/usr/local/Cellar/qt/4.8.3/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ mymainwindow.h -o moc_mymainwindow.cpp

moc_centralWidget.cpp: Texture.h \
		hertzStrokes/bitmap.h \
		imgSequence.h \
		imageGraph.h \
		jl_vectors.h \
		rotoCurves.h \
		rotoPath.h \
		dynArray.h \
		rotoCorresponder.h \
		geigerCorresponder.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h \
		joint.h \
		trackGraph.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		rotoRegion.h \
		drawCurves.h \
		drawPath.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		drawContCorr.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h \
		interModule.h \
		rotoscope.h \
		liveWire.h \
		heap.h \
		heap.C \
		transformer.h \
		draw.h \
		centralWidget.h
	/usr/local/Cellar/qt/4.8.3/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ centralWidget.h -o moc_centralWidget.cpp

moc_rotoscope.cpp: interModule.h \
		KLT/jl_vectors.h \
		KLT/dynArray.h \
		imageGraph.h \
		jl_vectors.h \
		liveWire.h \
		heap.h \
		heap.C \
		KLT/llist.h \
		KLT/llist.C \
		imgSequence.h \
		rotoCurves.h \
		rotoPath.h \
		dynArray.h \
		rotoCorresponder.h \
		geigerCorresponder.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/bezSpline.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h \
		joint.h \
		trackGraph.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		rotoRegion.h \
		drawCurves.h \
		drawPath.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		Texture.h \
		hertzStrokes/bitmap.h \
		drawContCorr.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h \
		transformer.h \
		rotoscope.h
	/usr/local/Cellar/qt/4.8.3/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ rotoscope.h -o moc_rotoscope.cpp

moc_liveWire.cpp: KLT/jl_vectors.h \
		imageGraph.h \
		jl_vectors.h \
		heap.h \
		heap.C \
		liveWire.h
	/usr/local/Cellar/qt/4.8.3/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ liveWire.h -o moc_liveWire.cpp

moc_draw.cpp: Texture.h \
		hertzStrokes/bitmap.h \
		imgSequence.h \
		imageGraph.h \
		jl_vectors.h \
		rotoCurves.h \
		rotoPath.h \
		dynArray.h \
		rotoCorresponder.h \
		geigerCorresponder.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h \
		joint.h \
		trackGraph.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		rotoRegion.h \
		drawCurves.h \
		drawPath.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		drawContCorr.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h \
		interModule.h \
		draw.h
	/usr/local/Cellar/qt/4.8.3/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ draw.h -o moc_draw.cpp

moc_interModule.cpp: KLT/jl_vectors.h \
		KLT/dynArray.h \
		interModule.h
	/usr/local/Cellar/qt/4.8.3/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ interModule.h -o moc_interModule.cpp

moc_rangeDialog.cpp: KLT/jl_vectors.h \
		rangeDialog.h
	/usr/local/Cellar/qt/4.8.3/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ rangeDialog.h -o moc_rangeDialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.C mymainwindow.h \
		imgSequence.h \
		imageGraph.h \
		jl_vectors.h \
		rotoCurves.h \
		rotoPath.h \
		dynArray.h \
		rotoCorresponder.h \
		geigerCorresponder.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h \
		joint.h \
		trackGraph.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		rotoRegion.h \
		drawCurves.h \
		drawPath.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		Texture.h \
		hertzStrokes/bitmap.h \
		drawContCorr.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h \
		centralWidget.h \
		interModule.h \
		rotoscope.h \
		liveWire.h \
		heap.h \
		heap.C \
		transformer.h \
		draw.h \
		rangeDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.C

mymainwindow.o: mymainwindow.C mymainwindow.h \
		imgSequence.h \
		imageGraph.h \
		jl_vectors.h \
		rotoCurves.h \
		rotoPath.h \
		dynArray.h \
		rotoCorresponder.h \
		geigerCorresponder.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h \
		joint.h \
		trackGraph.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		rotoRegion.h \
		drawCurves.h \
		drawPath.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		Texture.h \
		hertzStrokes/bitmap.h \
		drawContCorr.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h \
		centralWidget.h \
		interModule.h \
		rotoscope.h \
		liveWire.h \
		heap.h \
		heap.C \
		transformer.h \
		draw.h \
		rangeDialog.h \
		pixmaps.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mymainwindow.o mymainwindow.C

centralWidget.o: centralWidget.C centralWidget.h \
		Texture.h \
		hertzStrokes/bitmap.h \
		imgSequence.h \
		imageGraph.h \
		jl_vectors.h \
		rotoCurves.h \
		rotoPath.h \
		dynArray.h \
		rotoCorresponder.h \
		geigerCorresponder.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h \
		joint.h \
		trackGraph.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		rotoRegion.h \
		drawCurves.h \
		drawPath.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		drawContCorr.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h \
		interModule.h \
		rotoscope.h \
		liveWire.h \
		heap.h \
		heap.C \
		transformer.h \
		draw.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o centralWidget.o centralWidget.C

rotoscope.o: rotoscope.C rotoscope.h \
		interModule.h \
		KLT/jl_vectors.h \
		KLT/dynArray.h \
		imageGraph.h \
		jl_vectors.h \
		liveWire.h \
		heap.h \
		heap.C \
		KLT/llist.h \
		KLT/llist.C \
		imgSequence.h \
		rotoCurves.h \
		rotoPath.h \
		dynArray.h \
		rotoCorresponder.h \
		geigerCorresponder.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/bezSpline.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h \
		joint.h \
		trackGraph.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		rotoRegion.h \
		drawCurves.h \
		drawPath.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		Texture.h \
		hertzStrokes/bitmap.h \
		drawContCorr.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h \
		transformer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rotoscope.o rotoscope.C

imageGraph.o: imageGraph.C imageGraph.h \
		jl_vectors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imageGraph.o imageGraph.C

liveWire.o: liveWire.C liveWire.h \
		KLT/jl_vectors.h \
		imageGraph.h \
		jl_vectors.h \
		heap.h \
		heap.C
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o liveWire.o liveWire.C

rotoCurves.o: rotoCurves.C rotoCurves.h \
		rotoPath.h \
		jl_vectors.h \
		dynArray.h \
		rotoCorresponder.h \
		geigerCorresponder.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h \
		imgSequence.h \
		imageGraph.h \
		drawCurves.h \
		drawPath.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		Texture.h \
		hertzStrokes/bitmap.h \
		drawContCorr.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h \
		joint.h \
		trackGraph.h \
		rotoRegion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rotoCurves.o rotoCurves.C

imgSequence.o: imgSequence.C imgSequence.h \
		imageGraph.h \
		jl_vectors.h \
		rotoCurves.h \
		rotoPath.h \
		dynArray.h \
		rotoCorresponder.h \
		geigerCorresponder.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h \
		joint.h \
		trackGraph.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		rotoRegion.h \
		drawCurves.h \
		drawPath.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		Texture.h \
		hertzStrokes/bitmap.h \
		drawContCorr.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o imgSequence.o imgSequence.C

corresponder.o: corresponder.C corresponder.h \
		KLT/dynArray.h \
		KLT/jl_vectors.h \
		abstractPath.h \
		dynArray.h \
		jl_vectors.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/bezSpline.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o corresponder.o corresponder.C

draw.o: draw.C draw.h \
		Texture.h \
		hertzStrokes/bitmap.h \
		imgSequence.h \
		imageGraph.h \
		jl_vectors.h \
		rotoCurves.h \
		rotoPath.h \
		dynArray.h \
		rotoCorresponder.h \
		geigerCorresponder.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h \
		joint.h \
		trackGraph.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		rotoRegion.h \
		drawCurves.h \
		drawPath.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		drawContCorr.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h \
		interModule.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o draw.o draw.C

drawPath.o: drawPath.C drawPath.h \
		geigerCorresponder.h \
		dynArray.h \
		jl_vectors.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h \
		rotoCurves.h \
		rotoPath.h \
		rotoCorresponder.h \
		imgSequence.h \
		imageGraph.h \
		drawCurves.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h \
		joint.h \
		trackGraph.h \
		rotoRegion.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		Texture.h \
		hertzStrokes/bitmap.h \
		drawContCorr.h \
		drawCorresponder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawPath.o drawPath.C

drawCurves.o: drawCurves.C drawCurves.h \
		KLT/llist.h \
		KLT/llist.C \
		drawPath.h \
		geigerCorresponder.h \
		dynArray.h \
		jl_vectors.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h \
		rotoCurves.h \
		rotoPath.h \
		rotoCorresponder.h \
		imgSequence.h \
		imageGraph.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h \
		joint.h \
		trackGraph.h \
		rotoRegion.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		Texture.h \
		hertzStrokes/bitmap.h \
		drawContCorr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawCurves.o drawCurves.C

rotoPath.o: rotoPath.C rotoPath.h \
		jl_vectors.h \
		dynArray.h \
		rotoCorresponder.h \
		geigerCorresponder.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h \
		imgSequence.h \
		imageGraph.h \
		rotoCurves.h \
		rotoRegion.h \
		drawCurves.h \
		drawPath.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		Texture.h \
		hertzStrokes/bitmap.h \
		drawContCorr.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h \
		joint.h \
		trackGraph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rotoPath.o rotoPath.C

Stroke.o: hertzStrokes/Stroke.cpp hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		Texture.h \
		hertzStrokes/bitmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Stroke.o hertzStrokes/Stroke.cpp

geigerCorresponder.o: geigerCorresponder.C geigerCorresponder.h \
		dynArray.h \
		jl_vectors.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o geigerCorresponder.o geigerCorresponder.C

abstractPath.o: abstractPath.C abstractPath.h \
		dynArray.h \
		jl_vectors.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o abstractPath.o abstractPath.C

interModule.o: interModule.C interModule.h \
		KLT/jl_vectors.h \
		KLT/dynArray.h \
		rangeDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o interModule.o interModule.C

FitCurves.o: myCurveFit/FitCurves.c myCurveFit/FitCurves.h \
		myCurveFit/GraphicsGems.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o FitCurves.o myCurveFit/FitCurves.c

GGVecLib.o: myCurveFit/GGVecLib.c myCurveFit/GraphicsGems.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o GGVecLib.o myCurveFit/GGVecLib.c

rangeDialog.o: rangeDialog.C rangeDialog.h \
		KLT/jl_vectors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rangeDialog.o rangeDialog.C

drawCorresponder.o: drawCorresponder.C drawCorresponder.h \
		rotoCurves.h \
		rotoPath.h \
		jl_vectors.h \
		dynArray.h \
		rotoCorresponder.h \
		geigerCorresponder.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h \
		imgSequence.h \
		imageGraph.h \
		drawCurves.h \
		drawPath.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		Texture.h \
		hertzStrokes/bitmap.h \
		drawContCorr.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h \
		joint.h \
		trackGraph.h \
		rotoRegion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawCorresponder.o drawCorresponder.C

rotoCorresponder.o: rotoCorresponder.C rotoCorresponder.h \
		geigerCorresponder.h \
		dynArray.h \
		jl_vectors.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rotoCorresponder.o rotoCorresponder.C

Texture.o: Texture.C Texture.h \
		hertzStrokes/bitmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Texture.o Texture.C

bitmap.o: hertzStrokes/bitmap.cpp hertzStrokes/bitmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bitmap.o hertzStrokes/bitmap.cpp

trackGraph.o: trackGraph.C trackGraph.h \
		rotoPath.h \
		jl_vectors.h \
		dynArray.h \
		rotoCorresponder.h \
		geigerCorresponder.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h \
		imgSequence.h \
		imageGraph.h \
		rotoCurves.h \
		rotoRegion.h \
		drawCurves.h \
		drawPath.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		Texture.h \
		hertzStrokes/bitmap.h \
		drawContCorr.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h \
		joint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o trackGraph.o trackGraph.C

drawContCorr.o: drawContCorr.C drawContCorr.h \
		rotoPath.h \
		jl_vectors.h \
		dynArray.h \
		rotoCorresponder.h \
		geigerCorresponder.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h \
		imgSequence.h \
		imageGraph.h \
		rotoCurves.h \
		rotoRegion.h \
		drawCurves.h \
		drawPath.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		Texture.h \
		hertzStrokes/bitmap.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h \
		joint.h \
		trackGraph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawContCorr.o drawContCorr.C

transformer.o: transformer.C transformer.h \
		bBoxf2D.h \
		KLT/jl_vectors.h \
		rotoPath.h \
		jl_vectors.h \
		dynArray.h \
		rotoCorresponder.h \
		geigerCorresponder.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		gcnode.h \
		imgSequence.h \
		imageGraph.h \
		rotoCurves.h \
		rotoRegion.h \
		drawCurves.h \
		drawPath.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		Texture.h \
		hertzStrokes/bitmap.h \
		drawContCorr.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h \
		joint.h \
		trackGraph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o transformer.o transformer.C

rotoRegion.o: rotoRegion.C rotoRegion.h \
		rotoPath.h \
		jl_vectors.h \
		dynArray.h \
		rotoCorresponder.h \
		geigerCorresponder.h \
		abstractPath.h \
		KLT/talkFitCurve.h \
		KLT/llist.h \
		KLT/llist.C \
		KLT/jl_vectors.h \
		KLT/bezSpline.h \
		KLT/dynArray.h \
		KLT/cubicEval.h \
		KLT/samples.h \
		bBoxf2D.h \
		gcnode.h \
		imgSequence.h \
		imageGraph.h \
		rotoCurves.h \
		drawCurves.h \
		drawPath.h \
		hertzStrokes/Stroke.h \
		hertzStrokes/Point.h \
		hertzStrokes/color.h \
		Texture.h \
		hertzStrokes/bitmap.h \
		drawContCorr.h \
		KLT/klt.h \
		KLT/error.h \
		KLT/mysparsemat.h \
		KLT/linearSolver.h \
		KLT/keeper.h \
		KLT/genKeeper.h \
		KLT/multiTrackData.h \
		KLT/multiSplineData.h \
		KLT/contCorr.h \
		KLT/myassert.h \
		KLT/multiKeeper.h \
		KLT/HB_Sweep.h \
		KLT/HB_OneCurve.h \
		KLT/splineKeeper.h \
		KLT/diagMatrix.h \
		KLT/multiDiagMatrix.h \
		KLT/buildingSplineKeeper.h \
		KLT/obsCache.h \
		KLT/pyramid.h \
		KLT/klt_util.h \
		KLT/kernels.h \
		KLT/kltSpline.h \
		joint.h \
		trackGraph.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rotoRegion.o rotoRegion.C

moc_mymainwindow.o: moc_mymainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mymainwindow.o moc_mymainwindow.cpp

moc_centralWidget.o: moc_centralWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_centralWidget.o moc_centralWidget.cpp

moc_rotoscope.o: moc_rotoscope.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rotoscope.o moc_rotoscope.cpp

moc_liveWire.o: moc_liveWire.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_liveWire.o moc_liveWire.cpp

moc_draw.o: moc_draw.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_draw.o moc_draw.cpp

moc_interModule.o: moc_interModule.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_interModule.o moc_interModule.cpp

moc_rangeDialog.o: moc_rangeDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rangeDialog.o moc_rangeDialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

